### ISSUE TITLE
[2.0.1] Snipe issue

### ISSUE THREAD

**Issue by dzik87** [PocketMobsters/MobBotTemp#26]
After latest update to 2.0.1 snipe stopped working completely. When i reverse to 2.0.0 is works flawless.

**Comment by IccymanGO** [comment]
Confirmed, same in my bot. All Config options for sniping are on but no attempts to snipe are made.

**Comment by PocketMobsters** [comment]
Sniping was broken by implementing mapobject caching. I'll remove it for sniping specifically in the next update.
