### ISSUE TITLE
Not triggering pokestops after a few minutes of running

### ISSUE THREAD

**Issue by MajorT1990** [PocketMobsters/MobBotTemp#3]
After a few minutes MobBot still visits the pokestops, but doesn't trigger them. Can be seen on the screen shot below (purple triggered, blue not)

![image](https://cloud.githubusercontent.com/assets/4175692/17645849/4de07098-61b1-11e6-965d-2e97887c785f.png)

**Comment by PocketMobsters** [comment]
Movement speed may be too high. Pathing only tries forts twice, if you're going too fast you may as well switch to teleport which will unsoftban you.
