### ISSUE TITLE
Get this error for logging in PTC account

### ISSUE THREAD

**Issue by sstrunks52005** [PocketMobsters/MobBotTemp#32]
[http://imgur.com/a/hR8K4](url)

My auth:
{
"AuthType": "Ptc",
"GoogleRefreshToken": "",
"GoogleUsername": null,
"GooglePassword": null,
"PtcUsername": "ex",
"PtcPassword": "ex",
"UseProxy": false,
"ProxyLogin": null,
"ProxyPass": null,
"ProxyUri": null
}

have tried variations of PTC ptc Ptc

**Comment by xfaustx** [comment]
link dead

**Comment by sstrunks52005** [comment]
http://imgur.com/a/hR8K4

**Comment by EmanueleCoppola** [comment]
It seems a perma-ban.

**Comment by xfaustx** [comment]
yeah got that one on ptc acc

**Comment by xfaustx** [comment]
Need to add FAQ about BANs

**Comment by Aymendje** [comment]
[FEATURE REQUEST] Maybe catch the error and print a custom message about being permabanned / IP banned / soft banned etc.? @PocketMobsters

**Comment by sstrunks52005** [comment]
It wasn't a ban
Was wrong password xD
thanks for everyone's help

PTC or ptc does not matter
