### ISSUE TITLE
Please move settings to auth.json file!

### ISSUE THREAD

**Issue by NeCx** [PocketMobsters/MobBotTemp#5]
This should be unique for accounts so should be stated in auth.json file.

**Comment by AileenLumina** [comment]
I disagree with this. Bot managers are there to provide this functionality.

**Comment by GNAAAAR** [comment]
I disagree as well. At every pokemobbot update, I simply need to copy paste my auth.json file into the new update; therefore I don't have to type again my logs.

**Comment by NeCx** [comment]
@AileenLumina This is not about providing. They can also provide it via auth.json file.
@GNAAAAR This means on every update, your device is changing. This is something bad, man.
The problem is the device you use should be unique. People are sharing their configs on forums or discord channels. Some idiots are just copying and pasting the whole file without condescending to change it. Therefore, same devices may run at the same time. The worst thing is that if that guy get banned, then you are in danger. On the other side, if I want to use someone else's config or new update has come, I should not need to modify config file all the time. I should just copy my auth.json file and run it. That's why why all my unique settings should be in auth.json file.

**Comment by Aymendje** [comment]
If @NeCx is speaking about the DeviceSettings json, than yes, I agree with him
its starting to get a pain to copy that field everytime I update, and if I want to share config, I must clean it so people dont use the same unique config I use
Also, if I use multiple bots, I would like copying the config to all of my bot, and not having to generate a new one each time for new DeviceSettings
But I disagree moving anything else from the config.json

**Comment by Aymendje** [comment]
@GNAAAAR I think @NeCx wasnt explicit enough with his issue
I think he means only the part where we list the device parameters, that shoud be static and never (or almost never) change
And not merging config with auth
@NeCx Its not really polite to dislike every comment that tells you "no", just keep that in mind next time ^^"

**Comment by PocketMobsters** [comment]
May happen soon.

**Comment by AileenLumina** [comment]
Yep, device settings should be unique for every account or you'll risk an ID ban (see https://trello.com/c/fng6Jb4A/ ). It's easier to do this if you have the device settings in auth.json. Looking forward to this being taken care of. :)

**Comment by GNAAAAR** [comment]
@NeCx Not sure why you tell me this. I indeed check if the config and auth file received an update and, if not, I simply put my auth file because I am lazy to write again my ptc logs.

Auth.json file ain't config.json file, just saying ~ Also I don't share my files with others.
