### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by gexus** [PocketMobsters/MobBotTemp#9]
Sometimes shows this error
[21:01:58] (INFO) Arriving to Pokestop: Flamingo Garden in (206m)
[21:02:11] (ERROR) Unexpected character encountered while parsing value: P. Path '', line 0, position 0.

**Comment by Arderos** [comment]
Same here

**Comment by FabryB** [comment]
It happens to me too, but only when with BOT VISUALIZER I try to get my Pokemon list

**Comment by Aymendje** [comment]
Its because of the Necro Visualiser, and it shoud not impact the bot in any way
Ignore the error for now I guess

**Comment by PhantomBug** [comment]
At my side, mobbot latest via forum, it throws this error as well:

{"Command":"GetPokemonSettings"}

**Comment by FabryB** [comment]
Thats' NOT an error, it's a log of the command received ...

**Comment by PhantomBug** [comment]
Ok, I'm sorry to bother.

Glad you guys are there.

Thanks

On Thu, Aug 18, 2016 at 12:09 PM, Fabrizio Bottino <notifications@github.com
